### ISSUE TITLE
Video: when available - It is available :-)

### ISSUE THREAD

**Issue by alexrjs** [okken/talks#1]
https://www.youtube.com/watch?v=2R1HELARjUk

**Comment by MiroVatov** [comment]
Sorry, What is this about??? Please give me more information ?

**Comment by alexrjs** [comment]
[README.md](https://github.com/okken/talks/tree/master/2020/pycon_2020#readme) -> video : when available <- it is available see link in my first comment ;-)

**Comment by okken** [comment]
thanks
